GIhtubactionsTest

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,9 +34,9 @@ jobs:
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2
 
-      - name: Dependencies Scan
-        #if: 1>2
-        run: mvn clean verify -DskipTests -Pcve
+      # - name: Dependencies Scan
+      #   #if: 1>2
+      #   run: mvn clean verify -DskipTests -Pcve
 
       - name: Unit Testing
         run: mvn test -Put
@@ -78,7 +78,19 @@ jobs:
 
       - name: Wait for deploy to finish
         #votre travail
-        run: echo "Wait 30s ... "
+        run: |
+          echo "Wait 30s ... "
+          sleep 30
+          echo "Fetching the Quality Gate status..."
+          QUALITY_GATE_STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=baamethgit" | jq -r '.projectStatus.status')
+            
+          # Check the Quality Gate status
+          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
+            echo "Quality Gate failed: $QUALITY_GATE_STATUS"
+            exit 1
+          else
+            echo "Quality Gate passed: $QUALITY_GATE_STATUS"
+          fi
 
       - name: Check deploy
         #verifier si le deploiement s'est bien passe
